***Naive Bayes for Spam email prediction***

In [40]:
#importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB 

#Creating a dataframe
df1 = pd.read_csv('train_cleaned-2.csv')

#Applying the lamba function to categorize the label
def categorize_label(label):
    if label == 1:
        return 'spam'
    else:
        return 'not spam'
    
df1['label'] = df1['label'].apply(categorize_label)
#Droped unnecessary column
df1.drop('cleaned-subject', axis=1, inplace=True)

In [41]:
df1.groupby('label').describe()

cleaned-text                   
                count unique    top freq
label                                   
not spam        28644  26374  vince  375
spam            10390  10015  hello   44

In [42]:
# Converting the label columns' values to spam=1 and not spam=0
df1['spam'] = df1['label'].apply(lambda x: 1 if x=='spam' else 0)
df1.head()
df1.rename(columns={'cleaned-text':'Text'}, inplace=True)
df1.update(df1['Text'])
df1

label                                               Text  spam
0      not spam  go until jurong point crazy available only in ...     0
1      not spam                            ok lar joking wif u oni     0
2          spam  free entry in 2 a wkly comp to win fa cup fina...     1
3      not spam        u dun say so early hor u c already then say     0
4      not spam  nah i dont think he go to usf he live around h...     0
...         ...                                                ...   ...
39180  not spam  finally ready to show you be proud to introduc...     0
39181  not spam  1 isilotm 325 for palm o pocket pc and windows...     0
39182  not spam  alert bait and switch anticounterfeiting bill ...     0
39183  not spam  oneten 271102 insignificant matter heavily ove...     0
39184  not spam  02 extension search 03 dumb message revisit 04...     0

[39185 rows x 3 columns]

In [45]:
X_train,X_test,y_train,y_test = train_test_split(df1.Text,df1.spam,test_size=0.25)
df1.dropna(inplace=True)
df1.isna().sum()    

label    0
Text     0
spam     0
dtype: int64

In [46]:
countvector = CountVectorizer()
x_train_ct = countvector.fit_transform(X_train.values)
x_train_ct.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [47]:
# We will use Multinomial Naive Bayes as our model
modelMB = MultinomialNB()
modelMB.fit(x_train_ct, y_train)

MultinomialNB()

In [48]:
# Pre-test notspam
email_notspam = ['hey wanna get some coffee?']
email_notspam_count = countvector.transform(email_notspam)
modelMB.predict(email_notspam_count)

array([0])

In [49]:
# Pre-test spam
email_spam = ['reward click claim prize free money coupon discount bonus offer only for you 100 Earn back order now limited time offer 50 off today only']
email_spam_count = countvector.transform(email_spam)
email_spam_count
modelMB.predict(email_spam_count)

array([1])

In [50]:
# Testing the model 
x_test_count = countvector.transform(X_test)
modelMB.score(x_test_count, y_test)

0.914847832769751